services:
  api:
    build: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/home/node/api
    extra_hosts:
       - "host.docker.internal:host-gateway"

  app:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - .frontend:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:13-alpine
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eteg
    ports:
      - "5432:5432"